/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.botoesdecontrole;

import java.lang.reflect.Array;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jose.ncdantas
 */
public class VendaComputador extends javax.swing.JFrame {

    /**
     * Creates new form VendaComputador
     */
    public VendaComputador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSO = new javax.swing.ButtonGroup();
        GrupoModelo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TglWindows = new javax.swing.JToggleButton();
        TglLinux = new javax.swing.JToggleButton();
        BtnConfirmar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rboPc = new javax.swing.JRadioButton();
        rboNotebook = new javax.swing.JRadioButton();
        rboServer = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        chkMousePad = new javax.swing.JCheckBox();
        chkTeclado = new javax.swing.JCheckBox();
        chkMouse = new javax.swing.JCheckBox();
        chkHeadset = new javax.swing.JCheckBox();
        cboTipoArmazenamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstServicos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(0));

        GrupoSO.add(TglWindows);
        TglWindows.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        TglWindows.setText("Windows");
        TglWindows.setActionCommand("Windows");
        TglWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglWindowsActionPerformed(evt);
            }
        });

        GrupoSO.add(TglLinux);
        TglLinux.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        TglLinux.setText("Linux");
        TglLinux.setActionCommand("Linux - Ubuntu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TglWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TglLinux, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TglWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TglLinux, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        BtnConfirmar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(0));

        GrupoModelo.add(rboPc);
        rboPc.setText("PC");
        rboPc.setActionCommand("Computador Desktop");
        rboPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboPcActionPerformed(evt);
            }
        });

        GrupoModelo.add(rboNotebook);
        rboNotebook.setText("Notebook");
        rboNotebook.setActionCommand("Notebook");
        rboNotebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboNotebookActionPerformed(evt);
            }
        });

        GrupoModelo.add(rboServer);
        rboServer.setText("Servidor");
        rboServer.setActionCommand("Servidor");
        rboServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rboPc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rboNotebook)
                .addGap(80, 80, 80)
                .addComponent(rboServer)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rboPc)
                    .addComponent(rboNotebook)
                    .addComponent(rboServer))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));

        chkMousePad.setText("Mouse Pad");

        chkTeclado.setText("Teclado Mecânico");

        chkMouse.setText("Mouse Wireless");

        chkHeadset.setText("Headset Wireless");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTeclado)
                    .addComponent(chkMousePad)
                    .addComponent(chkMouse)
                    .addComponent(chkHeadset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(chkMousePad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkTeclado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkMouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkHeadset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboTipoArmazenamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um tipo de Armazenamento", "HDD 240GB", "HDD 500GB", "HDD 1TB", "HDD 2TB", "SSD 120GB", "SSD 500GB", "SSD 1TB", "SSD 2TB" }));
        cboTipoArmazenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoArmazenamentoActionPerformed(evt);
            }
        });

        lstServicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Garantia de 2 anos em todas as peças", "Windows 10 Pro, Instalado", "Antivirus e pacote office" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstServicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 138, Short.MAX_VALUE)
                                .addComponent(BtnConfirmar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboTipoArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboTipoArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(BtnConfirmar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TglWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglWindowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TglWindowsActionPerformed

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        //  if(TglWindows.isSelected()){
        //     JOptionPane.showMessageDialog(this, "Botão Windows Selecionado");
        //  }else if(TglLinux.isSelected()){
        //      JOptionPane.showMessageDialog(this, "Botão Linux Selecionado");
        //   }else{
        //       JOptionPane.showMessageDialog(this, "Nenhum Botão Selecionado");
        //   }
        String modeloComputador = GrupoModelo.getSelection().getActionCommand();
        JOptionPane.showMessageDialog(this, "Você Selecionou: " + modeloComputador);

        String retorno = GrupoSO.getSelection().getActionCommand();
        JOptionPane.showMessageDialog(this, "Você Selecionou: " + retorno);

        String perifericos = " ";

        if (chkMousePad.isSelected()) {
            perifericos += "Mouse Pad Speed " + " ";
        }

        if (chkTeclado.isSelected()) {
            perifericos += "Teclado Logitech G915 TKL " + " ";
        }

        if (chkMouse.isSelected()) {
            perifericos += "Mouse G703 Wireless " + " ";
        }

        if (chkHeadset.isSelected()) {
            perifericos += "Headset Wireless Logitech G453 " + " ";
        }

        JOptionPane.showMessageDialog(this, "Você Selecionou: " + perifericos);

        int indice = cboTipoArmazenamento.getSelectedIndex();
        if (indice > 0) {
            String tipoArmazenamento = cboTipoArmazenamento.getSelectedItem().toString();
            JOptionPane.showMessageDialog(this, "Você selecionou: " + tipoArmazenamento);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Tipo de Armazenamento");
        }
        
  //      String itemJList = lstServicos.getSelectedValue();
  //      JOptionPane.showMessageDialog(this, itemJList);
          ArrayList<String> lstItens = (ArrayList<String>) lstServicos.getSelectedValuesList();
          
          
          //*----- For Each -----*
          String itensLista = " ";
          for (String item : lstItens) {
            itensLista += item + ",  ";
        }
          JOptionPane.showMessageDialog(this, itensLista);
 
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void rboPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboPcActionPerformed

    }//GEN-LAST:event_rboPcActionPerformed

    private void rboNotebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboNotebookActionPerformed

    }//GEN-LAST:event_rboNotebookActionPerformed

    private void rboServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboServerActionPerformed

    }//GEN-LAST:event_rboServerActionPerformed

    private void cboTipoArmazenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoArmazenamentoActionPerformed

    }//GEN-LAST:event_cboTipoArmazenamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaComputador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.ButtonGroup GrupoModelo;
    private javax.swing.ButtonGroup GrupoSO;
    private javax.swing.JToggleButton TglLinux;
    private javax.swing.JToggleButton TglWindows;
    private javax.swing.JComboBox<String> cboTipoArmazenamento;
    private javax.swing.JCheckBox chkHeadset;
    private javax.swing.JCheckBox chkMouse;
    private javax.swing.JCheckBox chkMousePad;
    private javax.swing.JCheckBox chkTeclado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstServicos;
    private javax.swing.JRadioButton rboNotebook;
    private javax.swing.JRadioButton rboPc;
    private javax.swing.JRadioButton rboServer;
    // End of variables declaration//GEN-END:variables
}
